// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD7dstGDLAyjZhJzHhCcS5-ndA3seU9dM',
    appId: '1:132616640078:web:fd562351f6e92ae1cc551f',
    messagingSenderId: '132616640078',
    projectId: 'flutter-ci-cd-7a908',
    authDomain: 'flutter-ci-cd-7a908.firebaseapp.com',
    storageBucket: 'flutter-ci-cd-7a908.firebasestorage.app',
    measurementId: 'G-VDV7WCWMX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6k_ltAcnkSM0VulnPB_q1hmLgovgZnxQ',
    appId: '1:132616640078:android:d1ae341a18a45b65cc551f',
    messagingSenderId: '132616640078',
    projectId: 'flutter-ci-cd-7a908',
    storageBucket: 'flutter-ci-cd-7a908.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGNdAJmpj-nTgal09S3gWeI5NOwsoY3qE',
    appId: '1:132616640078:ios:38b329e0fc2585e4cc551f',
    messagingSenderId: '132616640078',
    projectId: 'flutter-ci-cd-7a908',
    storageBucket: 'flutter-ci-cd-7a908.firebasestorage.app',
    iosBundleId: 'com.example.flutterCiCd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGNdAJmpj-nTgal09S3gWeI5NOwsoY3qE',
    appId: '1:132616640078:ios:38b329e0fc2585e4cc551f',
    messagingSenderId: '132616640078',
    projectId: 'flutter-ci-cd-7a908',
    storageBucket: 'flutter-ci-cd-7a908.firebasestorage.app',
    iosBundleId: 'com.example.flutterCiCd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD7dstGDLAyjZhJzHhCcS5-ndA3seU9dM',
    appId: '1:132616640078:web:2b9159a8073505f7cc551f',
    messagingSenderId: '132616640078',
    projectId: 'flutter-ci-cd-7a908',
    authDomain: 'flutter-ci-cd-7a908.firebaseapp.com',
    storageBucket: 'flutter-ci-cd-7a908.firebasestorage.app',
    measurementId: 'G-32QSV26MNC',
  );
}
